name: Build macOS Intel Executable

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-macos-intel:
    name: Build for macOS Intel (x86_64)
    runs-on: macos-latest # Sẽ là ARM64, Python x86_64 chạy qua Rosetta 2

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up Python for x86_64 on macOS
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.10' # Chỉ định phiên bản vá lỗi cụ thể
          architecture: 'x86_64'   # Yêu cầu kiến trúc x86_64

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          if [ -f requirements.txt ]; then 
            pip install -r requirements.txt
          else
            echo "requirements.txt not found, skipping."
          fi

      - name: Run PyInstaller for macOS Intel
        run: |
          python -m PyInstaller --windowed \
                      --name "QuanLyKhamBenh" \
                      --add-data "patients_data.csv:." \
                      --add-data "doctors_data.csv:." \
                      --add-data "clinics_data.csv:." \
                      --clean \
                      --noconfirm \
                      --target-arch x86_64 \
                      main_gui.py
          
          echo "PyInstaller build for Intel macOS completed. Zipping the .app bundle..."
          zip -r ./QuanLyKhamBenh-macOS-Intel.zip ./dist/QuanLyKhamBenh.app

      - name: Upload macOS Intel artifact
        uses: actions/upload-artifact@v4
        with:
          name: QuanLyKhamBenh-macOS-Intel-app
          path: ./QuanLyKhamBenh-macOS-Intel.zip
