# --- JOB: Build cho macOS Intel (x86_64) ---
  build-macos-intel:
    name: Build for macOS Intel (x86_64)
    # Sử dụng runner macOS mới nhất (ARM64), Rosetta 2 sẽ được dùng cho Python x86_64
    runs-on: macos-latest # Hoặc macos-14 

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up Python for x86_64 on macOS
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          architecture: 'x86_64' # Quan trọng: Yêu cầu cài đặt Python kiến trúc x86_64

      - name: Install macOS Intel dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run PyInstaller for macOS Intel
        run: |
          # Python đang chạy ở đây là x86_64 (do actions/setup-python với architecture: 'x86_64')
          python -m PyInstaller --windowed \
                      --name "QuanLyKhamBenh" \
                      --add-data "patients_data.csv:." \
                      --add-data "doctors_data.csv:." \
                      --add-data "clinics_data.csv:." \
                      --clean \
                      --noconfirm \
                      --target-arch x86_64 \
                      main_gui.py
          # Tạo file zip cho .app để dễ dàng tải lên và tương thích với artifact
          zip -r ./QuanLyKhamBenh-macOS-Intel.zip ./dist/QuanLyKhamBenh.app

      - name: Upload macOS Intel artifact
        uses: actions/upload-artifact@v4
        with:
          name: QuanLyKhamBenh-macOS-Intel-app
          path: ./QuanLyKhamBenh-macOS-Intel.zip # Tải lên file zip của .app
