name: Build macOS Silicon Executable

on:
  push:
    branches:
      - main # Hoặc branch chính của bạn
      # - develop # Bạn có thể thêm các branch khác nếu muốn
  workflow_dispatch: # Cho phép chạy thủ công từ tab Actions trên GitHub

jobs:
  build-macos-silicon:
    name: Build for macOS Apple Silicon (ARM64)
    runs-on: macos-14 # Runner này là Apple Silicon (ARM64) based, macos-latest thường cũng trỏ về đây

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12' # Đảm bảo phiên bản này khớp với Python bạn dùng

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          # Đảm bảo file requirements.txt có trong kho chứa của bạn
          # và chứa các thư viện như customtkinter, darkdetect, v.v.
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run PyInstaller for macOS Silicon
        run: |
          python -m PyInstaller --windowed \
                      --name "QuanLyKhamBenh" \
                      --add-data "patients_data.csv:." \
                      --add-data "doctors_data.csv:." \
                      --add-data "clinics_data.csv:." \
                      --clean \
                      --noconfirm \ # Đã thêm cờ này để tự động xóa thư mục output cũ
                      --target-arch arm64 \
                      main_gui.py
          # Tạo file zip cho .app để dễ dàng tải lên và tương thích với artifact
          # Lệnh zip sẽ chạy sau khi PyInstaller hoàn tất thành công việc tạo .app
          zip -r ./QuanLyKhamBenh-macOS-Silicon.zip ./dist/QuanLyKhamBenh.app

      - name: Upload macOS Silicon artifact
        uses: actions/upload-artifact@v4
        with:
          name: QuanLyKhamBenh-macOS-Silicon-app
          path: ./QuanLyKhamBenh-macOS-Silicon.zip # Tải lên file zip của .app
